export const petTypes = {
  PET_INCREASED: "PET_INCREASED",
  PET_DECREASED: "PET_DECREASED",
  PET_FAVORITE_DECREASED: "PET_FAVORITE_DECREASED",
  PET_FAVORITE_INCREASED: "PET_FAVORITE_INCREASED",
};
